#include "pch.h"
#include "HookManager.h"

HookManager::HookManager(Pipe* pPipe)
{
    DetourRestoreAfterWith();

    DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread());

    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pMessageBoxA, HookUtil::DetouredFunctions::MessageBoxA_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pAccept, HookUtil::DetouredFunctions::accept_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pAdjustTokenPrivileges, HookUtil::DetouredFunctions::AdjustTokenPrivileges_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pAttachThreadInput, HookUtil::DetouredFunctions::AttachThreadInput_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pBind, HookUtil::DetouredFunctions::bind_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pBitBlt, HookUtil::DetouredFunctions::BitBlt_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCertOpenSystemStoreA, HookUtil::DetouredFunctions::CertOpenSystemStoreA_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCertOpenSystemStoreW, HookUtil::DetouredFunctions::CertOpenSystemStoreW_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pConnect, HookUtil::DetouredFunctions::connect_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pConnectNamedPipe, HookUtil::DetouredFunctions::ConnectNamedPipe_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pControlService, HookUtil::DetouredFunctions::ControlService_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCreateFile, HookUtil::DetouredFunctions::CreateFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCreateProcess, HookUtil::DetouredFunctions::CreateProcess_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCreateRemoteThread, HookUtil::DetouredFunctions::CreateRemoteThread_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCreateService, HookUtil::DetouredFunctions::CreateService_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCreateToolhelp32Snapshot, HookUtil::DetouredFunctions::CreateToolhelp32Snapshot_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pCryptAcquireContext, HookUtil::DetouredFunctions::CryptAcquireContext_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pDeviceIoControl, HookUtil::DetouredFunctions::DeviceIoControl_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pEnumProcesses, HookUtil::DetouredFunctions::EnumProcesses_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pEnumProcessModules, HookUtil::DetouredFunctions::EnumProcessModules_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pFindFirstFile, HookUtil::DetouredFunctions::FindFirstFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pFindNextFile, HookUtil::DetouredFunctions::FindNextFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pFindResource, HookUtil::DetouredFunctions::FindResource_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pFindWindow, HookUtil::DetouredFunctions::FindWindow_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pFtpPutFile, HookUtil::DetouredFunctions::FtpPutFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetAdaptersInfo, HookUtil::DetouredFunctions::GetAdaptersInfo_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetAsyncKeyState, HookUtil::DetouredFunctions::GetAsyncKeyState_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetDC, HookUtil::DetouredFunctions::GetDC_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetForegroundWindow, HookUtil::DetouredFunctions::GetForegroundWindow_Detour);
    //DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGethostbyname, HookUtil::DetouredFunctions::gethostbyname_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGethostname, HookUtil::DetouredFunctions::gethostname_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetKeyState, HookUtil::DetouredFunctions::GetKeyState_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetModuleFileName, HookUtil::DetouredFunctions::GetModuleFileName_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetModuleHandle, HookUtil::DetouredFunctions::GetModuleHandle_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetProcAddress, HookUtil::DetouredFunctions::GetProcAddress_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetStartupInfo, HookUtil::DetouredFunctions::GetStartupInfo_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetSystemDefaultLangID, HookUtil::DetouredFunctions::GetSystemDefaultLangID_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetTempPath, HookUtil::DetouredFunctions::GetTempPath_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetThreadContext, HookUtil::DetouredFunctions::GetThreadContext_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pGetWindowsDirectory, HookUtil::DetouredFunctions::GetWindowsDirectory_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pinet_addr, HookUtil::DetouredFunctions::inet_addr_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pInternetOpen, HookUtil::DetouredFunctions::InternetOpen_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pInternetOpenUrl, HookUtil::DetouredFunctions::InternetOpenUrl_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pInternetReadFile, HookUtil::DetouredFunctions::InternetReadFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pInternetWriteFile, HookUtil::DetouredFunctions::InternetWriteFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pIsUserAnAdmin, HookUtil::DetouredFunctions::IsUserAnAdmin_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pIsWow64Process, HookUtil::DetouredFunctions::IsWow64Process_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pLoadResource, HookUtil::DetouredFunctions::LoadResource_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pLsaEnumerateLogonSessions, HookUtil::DetouredFunctions::LsaEnumerateLogonSessions_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pMapViewOfFile, HookUtil::DetouredFunctions::MapViewOfFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pMapVirtualKey, HookUtil::DetouredFunctions::MapVirtualKey_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pModule32First, HookUtil::DetouredFunctions::Module32First_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pModule32Next, HookUtil::DetouredFunctions::Module32Next_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pNetScheduleJobAdd, HookUtil::DetouredFunctions::NetScheduleJobAdd_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pNetShareEnum, HookUtil::DetouredFunctions::NetShareEnum_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pOpenMutex, HookUtil::DetouredFunctions::OpenMutex_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pOpenProcess, HookUtil::DetouredFunctions::OpenProcess_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pOutputDebugString, HookUtil::DetouredFunctions::OutputDebugString_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pPeekNamedPipe, HookUtil::DetouredFunctions::PeekNamedPipe_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pProcess32First, HookUtil::DetouredFunctions::Process32First_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pProcess32Next, HookUtil::DetouredFunctions::Process32Next_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pQueueUserAPC, HookUtil::DetouredFunctions::QueueUserAPC_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pReadProcessMemory, HookUtil::DetouredFunctions::ReadProcessMemory_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pRecv, HookUtil::DetouredFunctions::recv_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pRegisterHotKey, HookUtil::DetouredFunctions::RegisterHotKey_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pRegOpenKey, HookUtil::DetouredFunctions::RegOpenKey_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pResumeThread, HookUtil::DetouredFunctions::ResumeThread_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pSend, HookUtil::DetouredFunctions::send_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pSetFileTime, HookUtil::DetouredFunctions::SetFileTime_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pSetThreadContext, HookUtil::DetouredFunctions::SetThreadContext_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pSetWindowsHookEx, HookUtil::DetouredFunctions::SetWindowsHookEx_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pShellExecute, HookUtil::DetouredFunctions::ShellExecute_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pStartServiceCtrlDispatcher, HookUtil::DetouredFunctions::StartServiceCtrlDispatcher_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pSuspendThread, HookUtil::DetouredFunctions::SuspendThread_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pSystem, HookUtil::DetouredFunctions::system_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pThread32First, HookUtil::DetouredFunctions::Thread32First_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pThread32Next, HookUtil::DetouredFunctions::Thread32Next_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pToolhelp32ReadProcessMemory, HookUtil::DetouredFunctions::Toolhelp32ReadProcessMemory_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pURLDownloadToFile, HookUtil::DetouredFunctions::URLDownloadToFile_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pVirtualAllocEx, HookUtil::DetouredFunctions::VirtualAllocEx_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pVirtualProtectEx, HookUtil::DetouredFunctions::VirtualProtectEx_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pWideCharToMultiByte, HookUtil::DetouredFunctions::WideCharToMultiByte_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pWinExec, HookUtil::DetouredFunctions::WinExec_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pWriteProcessMemory, HookUtil::DetouredFunctions::WriteProcessMemory_Detour);
    DetourAttach(&(PVOID&)HookUtil::FunctionPointers::pWSAStartup, HookUtil::DetouredFunctions::WSAStartup_Detour);

    DetourTransactionCommit();

    pPipe->SendMessage(LP_TEXT_STRING("Detours hooks initalised."));
}

HookManager::~HookManager()
{
    DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread());
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pMessageBoxA, HookUtil::DetouredFunctions::MessageBoxA_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pAccept, HookUtil::DetouredFunctions::accept_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pAdjustTokenPrivileges, HookUtil::DetouredFunctions::AdjustTokenPrivileges_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pAttachThreadInput, HookUtil::DetouredFunctions::AttachThreadInput_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pBind, HookUtil::DetouredFunctions::bind_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pBitBlt, HookUtil::DetouredFunctions::BitBlt_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCertOpenSystemStoreA, HookUtil::DetouredFunctions::CertOpenSystemStoreA_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCertOpenSystemStoreW, HookUtil::DetouredFunctions::CertOpenSystemStoreW_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pConnect, HookUtil::DetouredFunctions::connect_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pConnectNamedPipe, HookUtil::DetouredFunctions::ConnectNamedPipe_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pControlService, HookUtil::DetouredFunctions::ControlService_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCreateFile, HookUtil::DetouredFunctions::CreateFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCreateProcess, HookUtil::DetouredFunctions::CreateProcess_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCreateRemoteThread, HookUtil::DetouredFunctions::CreateRemoteThread_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCreateService, HookUtil::DetouredFunctions::CreateService_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCreateToolhelp32Snapshot, HookUtil::DetouredFunctions::CreateToolhelp32Snapshot_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pCryptAcquireContext, HookUtil::DetouredFunctions::CryptAcquireContext_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pDeviceIoControl, HookUtil::DetouredFunctions::DeviceIoControl_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pEnumProcesses, HookUtil::DetouredFunctions::EnumProcesses_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pEnumProcessModules, HookUtil::DetouredFunctions::EnumProcessModules_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pFindFirstFile, HookUtil::DetouredFunctions::FindFirstFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pFindNextFile, HookUtil::DetouredFunctions::FindNextFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pFindResource, HookUtil::DetouredFunctions::FindResource_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pFindWindow, HookUtil::DetouredFunctions::FindWindow_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pFtpPutFile, HookUtil::DetouredFunctions::FtpPutFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetAdaptersInfo, HookUtil::DetouredFunctions::GetAdaptersInfo_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetAsyncKeyState, HookUtil::DetouredFunctions::GetAsyncKeyState_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetDC, HookUtil::DetouredFunctions::GetDC_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetForegroundWindow, HookUtil::DetouredFunctions::GetForegroundWindow_Detour);
    //DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGethostbyname, HookUtil::DetouredFunctions::gethostbyname_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGethostname, HookUtil::DetouredFunctions::gethostname_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetKeyState, HookUtil::DetouredFunctions::GetKeyState_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetModuleFileName, HookUtil::DetouredFunctions::GetModuleFileName_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetModuleHandle, HookUtil::DetouredFunctions::GetModuleHandle_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetProcAddress, HookUtil::DetouredFunctions::GetProcAddress_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetStartupInfo, HookUtil::DetouredFunctions::GetStartupInfo_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetSystemDefaultLangID, HookUtil::DetouredFunctions::GetSystemDefaultLangID_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetTempPath, HookUtil::DetouredFunctions::GetTempPath_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetThreadContext, HookUtil::DetouredFunctions::GetThreadContext_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pGetWindowsDirectory, HookUtil::DetouredFunctions::GetWindowsDirectory_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pinet_addr, HookUtil::DetouredFunctions::inet_addr_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pInternetOpen, HookUtil::DetouredFunctions::InternetOpen_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pInternetOpenUrl, HookUtil::DetouredFunctions::InternetOpenUrl_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pInternetReadFile, HookUtil::DetouredFunctions::InternetReadFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pInternetWriteFile, HookUtil::DetouredFunctions::InternetWriteFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pIsUserAnAdmin, HookUtil::DetouredFunctions::IsUserAnAdmin_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pIsWow64Process, HookUtil::DetouredFunctions::IsWow64Process_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pLoadResource, HookUtil::DetouredFunctions::LoadResource_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pLsaEnumerateLogonSessions, HookUtil::DetouredFunctions::LsaEnumerateLogonSessions_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pMapViewOfFile, HookUtil::DetouredFunctions::MapViewOfFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pMapVirtualKey, HookUtil::DetouredFunctions::MapVirtualKey_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pModule32First, HookUtil::DetouredFunctions::Module32First_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pModule32Next, HookUtil::DetouredFunctions::Module32Next_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pNetScheduleJobAdd, HookUtil::DetouredFunctions::NetScheduleJobAdd_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pNetShareEnum, HookUtil::DetouredFunctions::NetShareEnum_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pOpenMutex, HookUtil::DetouredFunctions::OpenMutex_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pOpenProcess, HookUtil::DetouredFunctions::OpenProcess_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pOutputDebugString, HookUtil::DetouredFunctions::OutputDebugString_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pPeekNamedPipe, HookUtil::DetouredFunctions::PeekNamedPipe_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pProcess32First, HookUtil::DetouredFunctions::Process32First_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pProcess32Next, HookUtil::DetouredFunctions::Process32Next_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pQueueUserAPC, HookUtil::DetouredFunctions::QueueUserAPC_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pReadProcessMemory, HookUtil::DetouredFunctions::ReadProcessMemory_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pRecv, HookUtil::DetouredFunctions::recv_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pRegisterHotKey, HookUtil::DetouredFunctions::RegisterHotKey_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pRegOpenKey, HookUtil::DetouredFunctions::RegOpenKey_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pResumeThread, HookUtil::DetouredFunctions::ResumeThread_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pSend, HookUtil::DetouredFunctions::send_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pSetFileTime, HookUtil::DetouredFunctions::SetFileTime_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pSetThreadContext, HookUtil::DetouredFunctions::SetThreadContext_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pSetWindowsHookEx, HookUtil::DetouredFunctions::SetWindowsHookEx_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pShellExecute, HookUtil::DetouredFunctions::ShellExecute_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pStartServiceCtrlDispatcher, HookUtil::DetouredFunctions::StartServiceCtrlDispatcher_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pSuspendThread, HookUtil::DetouredFunctions::SuspendThread_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pSystem, HookUtil::DetouredFunctions::system_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pThread32First, HookUtil::DetouredFunctions::Thread32First_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pThread32Next, HookUtil::DetouredFunctions::Thread32Next_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pToolhelp32ReadProcessMemory, HookUtil::DetouredFunctions::Toolhelp32ReadProcessMemory_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pURLDownloadToFile, HookUtil::DetouredFunctions::URLDownloadToFile_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pVirtualAllocEx, HookUtil::DetouredFunctions::VirtualAllocEx_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pVirtualProtectEx, HookUtil::DetouredFunctions::VirtualProtectEx_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pWideCharToMultiByte, HookUtil::DetouredFunctions::WideCharToMultiByte_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pWinExec, HookUtil::DetouredFunctions::WinExec_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pWriteProcessMemory, HookUtil::DetouredFunctions::WriteProcessMemory_Detour);
    DetourDetach(&(PVOID&)HookUtil::FunctionPointers::pWSAStartup, HookUtil::DetouredFunctions::WSAStartup_Detour);
    DetourTransactionCommit();

    delete pHookManager;
}